// Per-task strategy recommendations, compiled from OSRS Wiki slayer-task and
// strategy pages (July 2026) for Ben's gear tier (whip/blowpipe/rune cbow,
// Ancient Magicks + Lunar unlocked, fairy rings + spirit trees, cannon owned).
// Keyed by Duradel task name (see tasks.ts). Fields marked unverified carry
// details the wiki search pass could not fully confirm.

export type LoadoutId = 'melee' | 'blowpipe' | 'crossbow' | 'burst'

export interface TaskStrategy {
  /** Which base gear setup to bring (see gearData.ts) */
  loadout: LoadoutId
  styleNote?: string
  /** Task-specific gear swaps/additions on top of the base setup */
  gearMods?: { slot: string; item: string; why: string }[]
  protectPrayer: string
  offensivePrayer: string
  cannon?: string
  bestLocation: { name: string; wikiPage: string; transport: string; why: string }
  altLocation?: { name: string; wikiPage: string; transport: string; why: string }
  /** Exact wiki item names to add to the inventory */
  inventoryExtras?: string[]
  /** Mandatory items — task fails or hurts without them */
  itemsRequired?: string[]
  dangers?: string[]
  strategy: string
  keyDrops?: string[]
  superior?: string
  bossAlt?: string
  /** 1 = sweaty, 5 = fully AFK */
  afk: number
  verdict: string
  unverified?: boolean
}

export const strategies: Record<string, TaskStrategy> = {
  'Aberrant spectres': {
    loadout: 'melee',
    gearMods: [{ slot: 'head', item: 'Slayer helmet (i)', why: 'Counts as a nose peg — MANDATORY or their stench drains stats through prayer' }],
    protectPrayer: 'Protect from Magic (fully neutralises them with the helm on)',
    offensivePrayer: 'Piety',
    cannon: 'Usable in the Stronghold Slayer Cave (single-way — safespot-cannon). Not in the Slayer Tower.',
    bestLocation: {
      name: 'Stronghold Slayer Cave',
      wikiPage: 'Stronghold Slayer Cave',
      transport: 'Slayer ring teleport, or spirit tree to Gnome Stronghold',
      why: 'Cannonable, tight spawns',
    },
    altLocation: {
      name: 'Slayer Tower (2nd floor)',
      wikiPage: 'Slayer Tower',
      transport: 'Slayer ring or Kharyrll teleport',
      why: 'Safespot on the brick pile west of the chain shortcut',
    },
    inventoryExtras: ['Herb sack', 'Cannonball', 'Prayer potion(4)'],
    itemsRequired: ['Nose peg or Slayer helmet'],
    dangers: ['Without nose peg/helm the stench hits through prayer and wrecks your stats'],
    strategy: 'Helm on, Protect from Magic, cannon centrally and whip them down. Pick up every herb — 60%+ herb drop rate, up to 3 at once.',
    keyDrops: ['Grimy herbs (constant)', 'Lava battlestaff', 'Mystic robe bottom (dark)'],
    superior: 'Abhorrent spectre',
    afk: 3,
    verdict: 'Good task — solid xp and herb profit.',
  },
  'Abyssal demons': {
    loadout: 'burst',
    styleNote: 'Burst for xp; whip at the Slayer Tower for AFK',
    gearMods: [
      { slot: 'head', item: 'Slayer helmet (i)', why: '15% magic accuracy/damage on task' },
      { slot: 'weapon', item: 'Ancient staff', why: 'Any ancients-capable staff for Ice Burst (Kodai wand is BiS)' },
    ],
    protectPrayer: 'Protect from Melee (they only melee, but teleport next to you)',
    offensivePrayer: 'Mystic Might / Augury (Piety if meleeing)',
    cannon: 'No cannon in the Catacombs or Slayer Tower.',
    bestLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's talisman or Kourend Castle teleport, drop at the statue",
      why: 'Dense multicombat — burst/barrage stacked demons',
    },
    altLocation: {
      name: 'Slayer Tower basement (task-only)',
      wikiPage: 'Slayer Tower',
      transport: 'Slayer ring teleport',
      why: 'AFK whip option; Morytania hard diary adds 10% slayer xp in the tower',
    },
    inventoryExtras: ['Nature rune', 'Prayer potion(4)', 'Ash sanctifier'],
    dangers: ['Their teleport shuffles stacks — keep Protect from Melee up while bursting'],
    strategy: 'Dance them into a pile in the Catacombs and Ice/Smoke Burst with Protect from Melee, or lazily whip them at the Tower.',
    keyDrops: ['Abyssal whip', 'Abyssal dagger', 'Abyssal head'],
    superior: 'Greater abyssal demon',
    bossAlt: 'Abyssal Sire (profitable, lower xp/hr)',
    afk: 3,
    verdict: 'Great task — extend it and burst for xp.',
  },
  Ankou: {
    loadout: 'burst',
    gearMods: [{ slot: 'neck', item: 'Salve amulet (ei)', why: 'Undead — beats the slayer helm bonus (they don\'t stack)' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Mystic Might / Augury',
    cannon: 'Usable everywhere except the Catacombs (e.g. Stronghold of Security level 4).',
    bestLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's talisman, south past the ghouls",
      why: 'Multicombat — stack and burst',
    },
    altLocation: {
      name: 'Stronghold of Security (level 4)',
      wikiPage: 'Stronghold of Security',
      transport: 'Barbarian Village',
      why: 'Ankou-only room, easy AFK melee',
    },
    inventoryExtras: ['Nature rune', 'Prayer potion(4)'],
    strategy: 'Dance into a stack and burst in the Catacombs — even extended tasks evaporate.',
    keyDrops: ['Death rune', 'Blood rune', 'Left skull half'],
    afk: 3,
    verdict: 'Fine quick task — burst and move on.',
  },
  Aquanites: {
    loadout: 'melee',
    gearMods: [{ slot: 'weapon', item: 'Abyssal whip', why: 'Open with slash to sever the lure (stab defence 60 → 10), then fast stab weapon if owned' }],
    protectPrayer: 'Protect from Magic (magic-only attackers)',
    offensivePrayer: 'Piety',
    cannon: 'No — single-way and the ground is too damp for a cannon.',
    bestLocation: {
      name: 'Ynysdail Cavern',
      wikiPage: 'Aquanite',
      transport: 'Sail to Ynysdail (73 Sailing, adamant keel+)',
      why: 'Only location',
    },
    inventoryExtras: ['Prayer potion(4)', 'Nature rune'],
    itemsRequired: ['78 Slayer', '73 Sailing', 'Lured In unlock (80 pts)'],
    dangers: ['Elder aquanite superior disables protection prayers and hits up to 50 — flick after each attack'],
    strategy: 'Melee under Protect from Magic: slash first to cut the lure, then kill. Ranged from 9+ tiles avoids all damage.',
    keyDrops: ['Aquanite tendon', 'Elder aquanite uniques'],
    superior: 'Elder aquanite',
    afk: 3,
    verdict: 'Only unlock with 73 Sailing; decent if you have it.',
    unverified: true,
  },
  Araxytes: {
    loadout: 'melee',
    gearMods: [{ slot: 'inventory', item: 'Extended anti-venom+(4)', why: 'They inflict escalating venom — immunity strongly recommended' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Works in the multicombat side caves (southern level-146 cave).',
    bestLocation: {
      name: 'Morytania Spider Cave (southern multi cave)',
      wikiPage: 'Araxyte',
      transport: "Drakan's medallion to Darkmeyer, entrance north-east",
      why: 'Kill only level 146s: doubled drops, doubled aranea boots rate, superior spawns',
    },
    inventoryExtras: ['Herb sack', 'Nature rune', 'Cannonball', 'Extended anti-venom+(4)'],
    itemsRequired: ['92 Slayer', 'Venom protection'],
    dangers: ['Venom stacks fast', 'Dreadborn Araxyte superior fires a globule hitting up to 50'],
    strategy: 'Skip the level 96s entirely. Camp the 146s with Protect from Melee, cannon in the multi cave, loot venom sacs and noted drops.',
    keyDrops: ['Aranea boots', 'Araxyte venom sac', 'Noted herbs/seeds'],
    superior: 'Dreadborn Araxyte',
    bossAlt: 'Araxxor (counts toward the task)',
    afk: 3,
    verdict: 'Great at 92+ — profitable and solid xp.',
    unverified: true,
  },
  Aviansies: {
    loadout: 'blowpipe',
    gearMods: [{ slot: 'body', item: "Armadyl chestplate", why: 'Any Armadyl item also calms aviansie aggression; blessed d\'hide is the budget pick' }],
    protectPrayer: 'Protect from Missiles',
    offensivePrayer: 'Rigour / Eagle Eye',
    cannon: 'Cannons cannot be set up in the God Wars Dungeon.',
    bestLocation: {
      name: 'God Wars Dungeon (aviansie chambers)',
      wikiPage: 'Aviansie',
      transport: 'Trollheim teleport, rope descent (first trip: rope + mith grapple)',
      why: 'Densest spawns; Protect from Missiles blocks nearly everything',
    },
    altLocation: {
      name: 'Wilderness God Wars Dungeon',
      wikiPage: 'Wilderness God Wars Dungeon',
      transport: 'Wilderness — PK risk',
      why: 'Noted adamantite bars without the diary',
    },
    inventoryExtras: ['Prayer potion(4)', 'Nature rune'],
    itemsRequired: ['Watch the birdie unlock (80 pts)', '70 Ranged (Armadyl area)', 'Death Plateau'],
    dangers: ['Multicombat god wars aggression — wear the right god items while moving'],
    strategy: 'Blowpipe under Protect from Missiles; loot addy bars (noted with Hard Fremennik diary) and runite limbs. Flying — ranged/magic only.',
    keyDrops: ['Adamantite bar', 'Rune limbs'],
    bossAlt: "Kree'arra",
    afk: 2,
    verdict: 'Mediocre xp, okay gp — skip unless doing Kree.',
  },
  Basilisks: {
    loadout: 'crossbow',
    gearMods: [{ slot: 'shield', item: "V's shield", why: "MANDATORY — mirror shield or V's shield, or their gaze drains stats and chunks you" }],
    protectPrayer: 'Protect from Magic (Basilisk Knights — stand out of melee range for zero damage)',
    offensivePrayer: 'Rigour / Eagle Eye',
    bestLocation: {
      name: "Jormungand's Prison (Basilisk Knights)",
      wikiPage: 'Basilisk Knight',
      transport: 'Rellekka teleport → Haskell sails you to the Island of Stone',
      why: 'Far better drops than regular basilisks — basilisk jaw at 1/1,000 on task',
    },
    altLocation: {
      name: 'Fremennik Slayer Dungeon',
      wikiPage: 'Fremennik Slayer Dungeon',
      transport: 'Fairy ring AJR',
      why: 'Regular basilisks — much worse, only pre-Fremennik Exiles',
    },
    inventoryExtras: ['Prayer potion(4)', 'Nature rune'],
    itemsRequired: ["Mirror shield or V's shield", 'The Fremennik Exiles (for Knights)'],
    strategy: 'Rune crossbow + V\'s shield at the Knights: stand outside the doorway 1-tile gap so they can only cast magic — Protect from Magic blocks it all. Damage-free.',
    keyDrops: ['Basilisk jaw (→ Neitiznot faceguard)', 'Rune alchables'],
    superior: 'Basilisk Sentinel',
    afk: 3,
    verdict: 'Good — do Knights for the jaw; skip regular basilisks.',
  },
  'Black demons': {
    loadout: 'blowpipe',
    gearMods: [{ slot: 'weapon', item: 'Arclight', why: 'Demonbane if meleeing instead' }],
    protectPrayer: 'Protect from Melee (irrelevant if safespotting)',
    offensivePrayer: 'Rigour (ranging) / Piety (melee)',
    cannon: 'Cannonable at Chasm of Fire and Taverley Dungeon; NOT in the Catacombs.',
    bestLocation: {
      name: 'Chasm of Fire (lowest level)',
      wikiPage: 'Chasm of Fire',
      transport: 'Fairy ring DJR',
      why: 'Multicombat + safespots + cannon = semi-AFK',
    },
    altLocation: {
      name: 'Taverley Dungeon',
      wikiPage: 'Taverley Dungeon',
      transport: 'Taverley house portal; 70 Agility shortcut',
      why: 'Packed spawns, cannonable',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)', 'Nature rune'],
    dangers: ['They hit ~16s with melee — stay out of range or pray'],
    strategy: 'Cannon from a safespot with the blowpipe on auto-retaliate. For profit, kill Demonic gorillas (they count) for zenyte shards.',
    keyDrops: ['Ensouled demon head', 'Zenyte shard (gorillas)'],
    bossAlt: 'Demonic gorillas or Skotizo (both count)',
    afk: 3,
    verdict: 'Decent with cannon; keep mainly for the gorilla option.',
  },
  'Black dragons': {
    loadout: 'melee',
    gearMods: [{ slot: 'shield', item: 'Anti-dragon shield', why: 'Mandatory dragonfire protection vs adults (babies breathe nothing)' }],
    protectPrayer: 'Protect from Melee vs adults; none for babies',
    offensivePrayer: 'Piety',
    cannon: 'Allowed in Taverley Dungeon.',
    bestLocation: {
      name: 'Taverley Dungeon (task-only baby black dragons)',
      wikiPage: 'Taverley Dungeon',
      transport: 'Taverley house portal / Falador teleport',
      why: 'Five baby spawns — AFK melee, no dragonfire protection needed, fastest clear',
    },
    altLocation: {
      name: 'Catacombs of Kourend (Brutal black dragons)',
      wikiPage: 'Brutal black dragon',
      transport: "Xeric's talisman",
      why: '77 Slayer; much more profitable, slower — crossbow + antifire',
    },
    inventoryExtras: ['Extended antifire(4)', 'Nature rune'],
    itemsRequired: ['Dragonfire protection vs adults'],
    strategy: 'Speed: AFK the babies in Taverley. Money: brutal blacks with crossbow + Protect from Magic. KBD counts too.',
    keyDrops: ['Black dragonhide', 'Dragon bones', 'Draconic visage (brutal/KBD)'],
    bossAlt: 'King Black Dragon',
    afk: 4,
    verdict: 'Quick via babies; brutals if you want gp.',
  },
  Bloodveld: {
    loadout: 'melee',
    gearMods: [{ slot: 'body', item: 'Proselyte hauberk', why: 'Their melee is magic-based — prayer bonus + Protect from Melee is the AFK meta' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Cannonable at Meiyerditch Laboratories and Stronghold Slayer Cave; not in the Catacombs.',
    bestLocation: {
      name: 'Meiyerditch Laboratories (Mutated Bloodvelds)',
      wikiPage: 'Meiyerditch Laboratories',
      transport: "Drakan's medallion to Ver Sinhaza",
      why: '7 mutated spawns in multicombat + cannon ≈ 60-70k slayer xp/hr, very AFK',
    },
    altLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's talisman",
      why: 'Cannon-free AFK pile with shards/totems',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)', 'Herb sack'],
    strategy: 'Kill mutated bloodvelds only (better table). Cannon at the Labs or AFK the Catacombs — one of the most AFK tasks in the game.',
    keyDrops: ['Blood rune', 'Grimy herbs'],
    superior: 'Insatiable bloodveld',
    afk: 5,
    verdict: 'Great — extend (Bleed me dry) and AFK it.',
  },
  'Blue dragons': {
    loadout: 'melee',
    gearMods: [{ slot: 'shield', item: 'Anti-dragon shield', why: 'Only needed for adults — babies breathe nothing' }],
    protectPrayer: 'None for babies; Protect from Melee or safespot for adults',
    offensivePrayer: 'Piety',
    cannon: 'Cannon the baby blues in Taverley Dungeon — the recommended fast clear.',
    bestLocation: {
      name: 'Taverley Dungeon',
      wikiPage: 'Taverley Dungeon',
      transport: 'Taverley house portal; 70 Agility pipe shortcut',
      why: 'Babies + cannon = fastest task; adults safespot easily for profit',
    },
    inventoryExtras: ['Cannonball', 'Nature rune'],
    strategy: 'Cannon babies for speed, safespot adults for bones+hides, or kill Vorkath (counts, post-DS2) for real money.',
    keyDrops: ['Dragon bones', 'Blue dragonhide'],
    bossAlt: 'Vorkath (after Dragon Slayer II)',
    afk: 3,
    verdict: 'Low xp — rush it, do Vorkath, or skip.',
  },
  'Cave horrors': {
    loadout: 'blowpipe',
    gearMods: [
      { slot: 'neck', item: 'Witchwood icon', why: 'MANDATORY — blocks the scream (10% of base HP per hit otherwise)' },
      { slot: 'inventory', item: 'Bullseye lantern', why: "Mos Le'Harmless Cave is dark — light source required" },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Rigour / Eagle Eye',
    cannon: 'Usable in the cave to speed things up.',
    bestLocation: {
      name: "Mos Le'Harmless Cave",
      wikiPage: "Mos Le'Harmless Cave",
      transport: "Mos le'harmless teleport scroll or charter ship (Cabin Fever)",
      why: 'Only location',
    },
    inventoryExtras: ['Herb sack', 'Cannonball', 'Nature rune'],
    itemsRequired: ['Witchwood icon', 'Light source', 'Cabin Fever'],
    strategy: 'Low HP and spread out — blowpipe with Protect from Melee, cannon if you want it done. Black mask money printer at 1/512.',
    keyDrops: ['Black mask (1/512)', 'Grimy herbs'],
    superior: 'Cave abomination',
    afk: 2,
    verdict: 'Low xp — you own a slayer helm already, so skip/block unless chasing mask gp.',
  },
  'Cave kraken': {
    loadout: 'burst',
    styleNote: 'Powered staff, not burst spells — magic only',
    gearMods: [{ slot: 'weapon', item: 'Trident of the seas', why: 'Magic is the ONLY effective style (ranged does 1/7 damage, melee can\'t reach)' }],
    protectPrayer: 'Protect from Magic',
    offensivePrayer: 'Mystic Might / Augury',
    bestLocation: {
      name: 'Kraken Cove',
      wikiPage: 'Kraken Cove',
      transport: 'Fairy ring AKQ, run west',
      why: 'Only location; task-only monsters',
    },
    inventoryExtras: ['Prayer potion(4)'],
    itemsRequired: ['87 Slayer', '50 Magic', 'Can only be attacked on-task'],
    strategy: 'Disturb a whirlpool and trident it down under Protect from Magic — one of the most AFK tasks in the game. Kill the Kraken boss for tentacles/tridents.',
    keyDrops: ['Uncharged trident of the seas (1/200)', 'Kraken tentacle (boss)'],
    bossAlt: 'Kraken',
    afk: 5,
    verdict: 'Never skip — super-AFK xp plus trident money.',
  },
  Dagannoth: {
    loadout: 'melee',
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: "Very effective at the Lighthouse basement and Jormungand's Prison; not in the Catacombs.",
    bestLocation: {
      name: "Jormungand's Prison (Island of Stone)",
      wikiPage: "Jormungand's Prison",
      transport: 'Rellekka → Haskell boat (The Fremennik Exiles)',
      why: 'Melee-only dagannoths in multicombat: cannon + Protect from Melee = fast xp, zero food',
    },
    altLocation: {
      name: 'Lighthouse basement',
      wikiPage: 'Lighthouse',
      transport: 'Fairy ring ALP',
      why: 'Multicombat + cannon; resupply food via Jossik',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)'],
    strategy: 'Cannon in the Prison with Protect from Melee and whip everything it tags — among the fastest slayer xp tasks.',
    keyDrops: ['Seeds/alchables', 'DK rings if bossing'],
    bossAlt: 'Dagannoth Kings',
    afk: 4,
    verdict: 'Great xp with a cannon — keep.',
  },

  // ── Batch B ────────────────────────────────────────────────────────────
  'Dark beasts': {
    loadout: 'melee',
    gearMods: [
      { slot: 'body', item: 'Proselyte hauberk', why: 'Prayer bonus sustains Protect from Melee on long trips' },
      { slot: 'legs', item: 'Proselyte cuisse', why: 'Prayer bonus' },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Allowed in Iorwerth Dungeon (single-way, adds DPS). Not in Mourner Tunnels.',
    bestLocation: {
      name: 'Iorwerth Dungeon',
      wikiPage: 'Iorwerth Dungeon',
      transport: 'Teleport crystal to Prifddinas (requires Song of the Elves)',
      why: 'Cannonable, bank nearby, 3-5 crystal shard drops',
    },
    altLocation: {
      name: 'Mourner Tunnels',
      wikiPage: 'Mourner Tunnels',
      transport: 'Slayer ring teleports straight to them (MEP II)',
      why: '19 dark beasts in the first stretch; the pre-SotE option',
    },
    inventoryExtras: ['Prayer potion(4)'],
    dangers: ['Always aggressive (no tolerance timer)', 'Switch to Magic if they can\'t reach you — stay in melee range'],
    strategy:
      'Whip them under Protect from Melee + Piety; they only cast magic when out of melee reach. High prayer-bonus armour makes it near-AFK.',
    keyDrops: ['Dark bow', 'Death rune', 'Grimy ranarr weed'],
    superior: 'Night beast',
    afk: 4,
    verdict: 'Solid — low effort, Dark bow chance, crystal shards in Prifddinas.',
  },
  Drakes: {
    loadout: 'melee',
    gearMods: [
      { slot: 'feet', item: 'Boots of stone', why: 'MANDATORY — the Karuulm floor burns you without stone/brimstone/granite boots (waived by elite Kourend diary)' },
      { slot: 'weapon', item: 'Dragon hunter lance', why: 'Dragonbane bonus — big upgrade over whip here if affordable' },
    ],
    protectPrayer: 'Protect from Missiles',
    offensivePrayer: 'Piety',
    cannon: 'No cannon in the Karuulm Slayer Dungeon.',
    bestLocation: {
      name: 'Karuulm Slayer Dungeon (middle level)',
      wikiPage: 'Karuulm Slayer Dungeon',
      transport: "Rada's blessing 3/4 or fairy ring CIR",
      why: 'Only drake location',
    },
    inventoryExtras: ['Prayer potion(4)', 'Super combat potion(4)'],
    itemsRequired: ['Boots of stone'],
    dangers: ['Tile-target fireball hits 6-8 ×4 — step off the marked tile when it launches'],
    strategy:
      'Melee under Protect from Missiles and sidestep the fireball. Claw and tooth drops are 5× more common on task.',
    keyDrops: ["Drake's claw", "Drake's tooth", 'Dragon knife'],
    superior: 'Guardian Drake',
    afk: 2,
    verdict: 'Profitable uniques, but needs attention — do when awake.',
  },
  'Dust devils': {
    loadout: 'burst',
    gearMods: [
      { slot: 'head', item: 'Slayer helmet (i)', why: 'MANDATORY face protection — without it they hit 16s and drain all combat stats' },
      { slot: 'neck', item: 'Occult necklace', why: '+10% magic damage for bursting' },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Augury (or Mystic Might)',
    cannon: 'Not allowed in the Catacombs — bursting is far better anyway.',
    bestLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's talisman (Xeric's Heart) or Kourend Castle teleport, drop down the statue",
      why: 'Multicombat stacking + ancient shard/dark totem drops',
    },
    altLocation: {
      name: 'Smoke Dungeon (Pollnivneach)',
      wikiPage: 'Smoke Dungeon',
      transport: 'Fairy ring DLQ, climb down the well',
      why: 'Alternative burst spot, weaker drop table',
    },
    inventoryExtras: ['Death rune', 'Chaos rune', 'Water rune', 'Prayer potion(4)'],
    itemsRequired: ['Slayer helmet (i) (or Facemask)'],
    strategy:
      'Tag with blowpipe, run around a corner so they clump, then Ice Burst/Barrage the pile under Protect from Melee. Top-tier Slayer AND Magic xp.',
    keyDrops: ['Dragon chainbody (v. rare)', 'Ancient shard', 'Dark totem piece'],
    superior: 'Choke devil',
    afk: 2,
    verdict: 'One of the best tasks in the game — extend it.',
  },
  Elves: {
    loadout: 'melee',
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Allowed in Iorwerth Dungeon (single-way; still adds DPS).',
    bestLocation: {
      name: 'Iorwerth Dungeon',
      wikiPage: 'Iorwerth Dungeon',
      transport: 'Teleport crystal to Prifddinas (requires Song of the Elves)',
      why: '13 warriors + crystal shard and enhanced teleport seed drops',
    },
    altLocation: {
      name: 'Iorwerth Camp',
      wikiPage: 'Iorwerth Camp',
      transport: 'Teleport crystal to Lletya, run west',
      why: 'Pre-SotE option; safespot halberd elves with ranged',
    },
    inventoryExtras: ['Prayer potion(4)', 'Cannonball'],
    dangers: ['Archers hit through Protect from Melee — position so only warriors see you'],
    strategy: 'Whip the warriors under Protect from Melee; elves are weak to stab/slash. Cannon speeds it up.',
    keyDrops: ['Crystal shard', 'Enhanced crystal teleport seed'],
    afk: 3,
    verdict: 'Good with Song of the Elves done (shards), mediocre otherwise.',
  },
  'Fire giants': {
    loadout: 'melee',
    gearMods: [{ slot: 'body', item: 'Proselyte hauberk', why: 'Prayer bonus for long AFK stints' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'No cannon in Catacombs; Stronghold Slayer Cave allows it for a fast task.',
    bestLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's Heart teleport, drop down the centre",
      why: 'Multicombat pack — AFK up to ~7 minutes with Protect from Melee',
    },
    altLocation: {
      name: 'Stronghold Slayer Cave',
      wikiPage: 'Stronghold Slayer Cave',
      transport: 'Slayer ring teleport',
      why: 'Cannonable for speed',
    },
    inventoryExtras: ['Prayer potion(4)', 'Bonecrusher'],
    strategy:
      'Stand in a Catacombs pack, Protect from Melee + Piety, and AFK; Bonecrusher on big bones sustains prayer. Royal Titans count as an alternative kill.',
    keyDrops: ['Rune scimitar', 'Ancient shard', 'Dark totem piece'],
    bossAlt: 'Royal Titans (Branda counts toward the task)',
    afk: 5,
    verdict: 'Perfect AFK filler — low gp, zero effort.',
  },
  'Fossil Island wyverns': {
    loadout: 'melee',
    gearMods: [
      { slot: 'shield', item: 'Dragonfire shield', why: 'Icy breath needs elemental/dragonfire/ancient wyvern shield — antifire potions and anti-dragon shield do NOT work' },
      { slot: 'body', item: 'Bandos chestplate', why: 'Max ranged defence — their ranged attack hits through prayer' },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Not usable in the Wyvern Cave (unverified).',
    bestLocation: {
      name: 'Wyvern Cave (task-only area)',
      wikiPage: 'Wyvern Cave',
      transport: 'Digsite pendant → House on the Hill → Magic Mushtree to Mushroom Meadow',
      why: 'Only location; all wyvern types present',
    },
    inventoryExtras: ['Prayer potion(4)', 'Super combat potion(4)'],
    itemsRequired: ['Dragonfire shield (or Elemental shield / Dragonfire ward / Ancient wyvern shield)'],
    dangers: ['Icy breath freezes and hits hard without the shield', 'Ranged chip damage through prayer — bring food'],
    strategy:
      'Tank in high ranged-defence gear with the dragonfire shield, pray Melee, eat through chip damage. Wyvern bones cover the supply cost.',
    keyDrops: ['Wyvern visage', 'Granite legs', 'Wyvern bones'],
    bossAlt: 'Ancient Wyvern variant (82 Slayer) counts',
    afk: 2,
    verdict: 'Marginal — okay gp, annoying chip damage. Skip candidate.',
    unverified: true,
  },
  'Frost dragons': {
    loadout: 'melee',
    gearMods: [
      { slot: 'weapon', item: 'Abyssal bludgeon', why: 'Weakest to crush (whip slash is suboptimal); fire spells also exploit 100% fire weakness' },
      { slot: 'shield', item: 'Anti-dragon shield', why: 'With antifire potion negates icy dragonfire (or super antifire alone)' },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    bestLocation: {
      name: 'Grimstone Dungeon (Isle of Grimstone)',
      wikiPage: 'Frost dragon',
      transport: 'Sail there (87 Sailing); fairy ring DLP after first mooring',
      why: 'Only location',
    },
    inventoryExtras: ['Super antifire potion(4)', 'Prayer potion(4)'],
    itemsRequired: ['Super antifire potion (or antifire + anti-dragon shield)', '87 Sailing'],
    dangers: ['Unprotected icy breath freezes you', 'Resistant to ranged — don\'t blowpipe'],
    strategy:
      'Melee-only + short-range breath means they safespot like chromatic dragons, or tank with super antifires. On-task dragon metal sheet rate improves 1/100 → 1/40.',
    keyDrops: ['Dragon metal sheet', 'Dragon nail', 'Frost dragon bones'],
    afk: 3,
    verdict: 'Strong gp if you have 87 Sailing; otherwise you can\'t even receive it.',
    unverified: true,
  },
  Gargoyles: {
    loadout: 'melee',
    gearMods: [{ slot: 'inventory', item: 'Rock hammer', why: 'MANDATORY — smash at ≤9 HP to finish kills (Gargoyle Smasher perk, 120 pts, automates it)' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Not worth it — the smash mechanic keeps it melee-standard.',
    bestLocation: {
      name: 'Slayer Tower basement (task-only)',
      wikiPage: 'Slayer Tower',
      transport: 'Slayer ring (Morytania Slayer Tower) or Kharyrll teleport',
      why: 'Dense task-only spawns',
    },
    altLocation: {
      name: 'Slayer Tower top floor',
      wikiPage: 'Gargoyle',
      transport: 'Same tower, climb up',
      why: 'Off-task accessible',
    },
    inventoryExtras: ['Rock hammer', 'Prayer potion(4)', 'Nature rune'],
    itemsRequired: ['Rock hammer'],
    strategy:
      'Whip under Protect from Melee — completely safe. Buy Gargoyle Smasher so kills auto-finish. Alchables rain: one of the best money tasks at this level.',
    keyDrops: ['Granite maul', 'Mystic robe top (dark)', 'Rune full helm', 'Brittle key'],
    superior: 'Marble gargoyle',
    bossAlt: 'Grotesque Guardians (Brittle key unlocks the roof)',
    afk: 4,
    verdict: 'Always do — excellent gp per effort.',
  },
  'Greater demons': {
    loadout: 'melee',
    gearMods: [{ slot: 'weapon', item: 'Arclight', why: 'Demonbane — cheap and much faster than whip on demons' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Chasm of Fire lowest floor is cannonable — fastest clear. Catacombs is not.',
    bestLocation: {
      name: 'Chasm of Fire (lowest floor)',
      wikiPage: 'Chasm of Fire',
      transport: 'Fairy ring DJR, short run',
      why: 'Cannonable and compact',
    },
    altLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's Heart teleport",
      why: 'AFK multicombat + shards/totems',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)', 'Ash sanctifier'],
    strategy:
      'Cannon + Arclight at the Chasm for speed, or AFK the Catacombs. K\'ril Tsutsaroth and Skotizo both count if you fancy a boss.',
    keyDrops: ['Rune full helm', 'Ancient shard', 'Dark totem piece'],
    bossAlt: "K'ril Tsutsaroth or Skotizo",
    afk: 4,
    verdict: 'Fast filler xp; Skotizo variant adds spice.',
  },
  Gryphons: {
    loadout: 'melee',
    gearMods: [{ slot: 'shield', item: 'Dragonfire shield', why: 'Heavy — helps pass the 30 kg worn-weight threshold that disables their knockback special' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Southern room of each cave is multicombat and cannonable.',
    bestLocation: {
      name: 'The Great Conch — eastern cavern (task-only)',
      wikiPage: 'The Great Conch',
      transport: 'Fairy ring CJQ, or moor at The Summer Shore (45 Sailing)',
      why: 'Best density',
    },
    altLocation: {
      name: 'The Great Conch — western cavern',
      wikiPage: 'The Great Conch',
      transport: 'Same island',
      why: 'Off-task accessible',
    },
    inventoryExtras: ['Prayer potion(4)', 'Cannonball'],
    itemsRequired: ['30+ kg worn weight (blocks knockback special)', 'Wings Spread unlock (80 pts)', '45 Sailing + Troubled Tortugans'],
    dangers: ['Knockback special displaces you and hits if worn weight < 30 kg', 'Dire gryphon superior needs a Tortugan shield to avoid guaranteed damage'],
    strategy:
      'Wear deliberately heavy melee gear so the special never fires; they\'re melee-only after that, so Protect from Melee trivialises the task. Feathers charge the Horn of plenty.',
    keyDrops: ['Gryphon feather'],
    superior: 'Dire gryphon',
    bossAlt: 'Shellbane gryphon (centre lair; bring Tortugan shield)',
    afk: 3,
    verdict: 'Fine if you have Sailing access; only unlock if you want feathers/boss.',
  },
  Hellhounds: {
    loadout: 'melee',
    gearMods: [{ slot: 'body', item: 'Proselyte hauberk', why: 'They drop nothing — max prayer bonus and AFK' }],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Stronghold Slayer Cave allows it — four rooms with safespots, fastest clear.',
    bestLocation: {
      name: 'Stronghold Slayer Cave',
      wikiPage: 'Stronghold Slayer Cave',
      transport: 'Slayer ring teleport',
      why: 'Cannonable; ~50-70k slayer xp/hr with cannon',
    },
    altLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's Heart teleport",
      why: 'AFK multicombat + shards/totems (no cannon)',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)', 'Holy wrench'],
    strategy:
      'Drops are just bones and clues, so cannon it away or AFK the Catacombs. At 91 Slayer take Cerberus instead — 2M+ gp/hr and BiS boot crystals. Bring Arclight/Emberlight for Cerb.',
    keyDrops: ['Hard clue scroll (1/64)', 'Primordial/Pegasian/Eternal crystal (Cerberus)'],
    bossAlt: 'Cerberus (91 Slayer)',
    afk: 4,
    verdict: 'Never block — it becomes a Cerberus task at 91.',
  },
  Kalphite: {
    loadout: 'melee',
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'The whole strategy — cannon workers (fast) or soldiers (xp).',
    bestLocation: {
      name: 'Kalphite Cave (task-only area)',
      wikiPage: 'Kalphite Cave',
      transport: 'Fairy ring BIQ, short run',
      why: 'Open chambers ideal for the cannon',
    },
    altLocation: {
      name: 'Kalphite Lair',
      wikiPage: 'Kalphite Lair',
      transport: 'Shantay Pass + carpet',
      why: 'Route to Kalphite Queen for the boss option',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)'],
    strategy: 'Drop the cannon in a worker chamber and watch combat-28 bugs evaporate. Avoid guardians (slow, poor xp).',
    keyDrops: ['Potato cactus', 'Hard clue scroll (guardians)'],
    bossAlt: 'Kalphite Queen',
    afk: 3,
    verdict: 'Fast cannon fodder — or a classic block candidate.',
  },
  Kurask: {
    loadout: 'melee',
    gearMods: [
      { slot: 'weapon', item: 'Leaf-bladed battleaxe', why: 'MANDATORY class — kurasks only take damage from leaf-bladed weapons, broad ammo, or Magic Dart' },
      { slot: 'ammo', item: 'Broad bolts', why: 'If ranging with the rune crossbow instead' },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Pointless — standard cannonballs can\'t damage leafy monsters (unverified).',
    bestLocation: {
      name: 'Fremennik Slayer Dungeon (task-only area)',
      wikiPage: 'Fremennik Slayer Dungeon',
      transport: 'Fairy ring AJR — entrance adjacent',
      why: 'Dense + ranged safespot behind rocks',
    },
    altLocation: {
      name: 'Iorwerth Dungeon',
      wikiPage: 'Iorwerth Dungeon',
      transport: 'Prifddinas teleport crystal (SotE)',
      why: '~7.5k gp/kill average with crystal shards',
    },
    inventoryExtras: ['Herb sack', 'Prayer potion(4)', 'Nature rune'],
    itemsRequired: ['Leaf-bladed battleaxe (or sword/spear, broad bolts, Magic Dart)'],
    strategy: 'They cannot hurt you under Protect from Melee. Chop away; triple herb drops feed the herb sack.',
    keyDrops: ['Leaf-bladed battleaxe', 'Mystic robe top (light)', 'Grimy herbs ×3'],
    superior: 'King kurask',
    afk: 4,
    verdict: 'Safe, profitable, near-AFK — a keeper.',
  },
  Lizardmen: {
    loadout: 'melee',
    gearMods: [
      { slot: 'head', item: 'Slayer helmet (i)', why: 'With hard Kourend & Kebos diary, Captain Cleive adds Shayzien protection to the helm — blocks shaman acid (up to 30)' },
      { slot: 'body', item: 'Shayzien platebody (5)', why: 'Alternative: full tier-5 Shayzien blocks 100% of acid' },
    ],
    protectPrayer: 'Protect from Missiles',
    offensivePrayer: 'Piety',
    cannon: 'Allowed at Lizardman Canyon (multicombat); not in the Molch shaman areas.',
    bestLocation: {
      name: 'Lizardman Canyon',
      wikiPage: 'Lizardman Canyon',
      transport: 'Battlefront teleport, run east',
      why: 'Multicombat + cannon = fast clear',
    },
    altLocation: {
      name: 'Lizardman Temple (Molch)',
      wikiPage: 'Lizardman Temple',
      transport: 'Fairy ring DJR → Molch',
      why: 'Shamans — Dragon warhammer hunting on task',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)', 'Antipoison(4)'],
    itemsRequired: ['Shayzien armour (5) or diary-boosted slayer helm — for shamans only', "'Reptile got ripped' unlock (75 pts)"],
    dangers: ['Shaman acid hits up to 30 through prayer without Shayzien protection', 'Dodge the jump attack and exploding spawns'],
    strategy:
      'Cannon regulars in the Canyon for speed, or hunt shamans at Molch with the diary helm for DWH rolls.',
    keyDrops: ['Dragon warhammer (shamans)', "Xeric's talisman"],
    afk: 2,
    verdict: 'Only unlock if you\'re hunting the Dragon warhammer.',
  },

  // ── Batch C ────────────────────────────────────────────────────────────
  'Metal dragons': {
    loadout: 'melee',
    gearMods: [
      { slot: 'shield', item: 'Anti-dragon shield', why: 'With an antifire potion, dragonfire hits 0' },
      { slot: 'weapon', item: 'Abyssal dagger', why: 'Metal dragons are weak to stab — whip slash is noticeably worse (Dragon hunter lance is BiS)' },
    ],
    protectPrayer: 'Optional with antifire + shield (Protect from Melee up close)',
    offensivePrayer: 'Piety',
    cannon: 'Cannon the slayer-only bronze dragon room in Brimhaven Dungeon. Not in the Catacombs.',
    bestLocation: {
      name: 'Brimhaven Dungeon (slayer-only bronze/iron area)',
      wikiPage: 'Brimhaven Dungeon',
      transport: 'Amulet of glory → Musa Point (entry 875 gp, free with Karamja diary)',
      why: '5 bronze spawns in a small cannonable room; irons adjacent for visage hunting',
    },
    altLocation: {
      name: 'Catacombs of Kourend',
      wikiPage: 'Catacombs of Kourend',
      transport: "Xeric's talisman",
      why: 'Shards/totems, no cannon',
    },
    inventoryExtras: ['Extended antifire(4)', 'Cannonball', 'Prayer potion(4)'],
    itemsRequired: ['Anti-dragon shield or DFS', 'Antifire potion'],
    dangers: ['Long-range dragonfire without BOTH protections', "Rune dragons' leech attack pierces prayer (Lithkren)"],
    strategy: 'One consolidated task since Aug 2025 — kill any tier. Cannon + stab melee on bronze/iron in Brimhaven for speed; iron+ can drop the visage; adamant/rune at Lithkren for profit if geared.',
    keyDrops: ['Draconic visage (iron+)', 'Dragon platelegs/skirt', 'Dragon limbs (rune)'],
    afk: 2,
    verdict: 'Heaviest weight at Duradel (14) and slow — the classic block candidate.',
  },
  'Mutated Zygomites': {
    loadout: 'melee',
    gearMods: [{ slot: 'body', item: "Black d'hide body", why: 'Their attacks roll vs magic defence — d\'hide cuts their accuracy' }],
    protectPrayer: 'None needed',
    offensivePrayer: 'Piety',
    cannon: 'Zygomites are immune to the cannon.',
    bestLocation: {
      name: 'Zanaris (near the Cosmic altar)',
      wikiPage: 'Zygomite',
      transport: 'Any fairy ring → Zanaris',
      why: 'Fast access; pillars allow safespotting',
    },
    altLocation: {
      name: 'Mushroom Forest, Fossil Island (Ancient Zygomites)',
      wikiPage: 'Ancient Zygomite',
      transport: 'Digsite pendant → mushtree network',
      why: 'Ancient variant also counts',
    },
    inventoryExtras: ['Fungicide spray 10', 'Fungicide'],
    itemsRequired: ['Fungicide spray 10 — they cannot die without being sprayed below 8 HP'],
    strategy: 'Fight near the Cosmic altar; drop each below 8 HP then use the fungicide spray. Refill the spray every ten kills.',
    keyDrops: ['Herbs and seeds (nothing notable)'],
    afk: 2,
    verdict: 'Short, easy, low value — do it for points, never extend.',
  },
  Nechryael: {
    loadout: 'burst',
    gearMods: [
      { slot: 'neck', item: 'Occult necklace', why: 'Very low magic defence — stack magic damage %' },
      { slot: 'body', item: 'Proselyte hauberk', why: 'Prayer bonus — you\'ll flick Protect from Melee constantly' },
    ],
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Augury / Mystic Might',
    cannon: 'No cannon in the Catacombs.',
    bestLocation: {
      name: 'Catacombs of Kourend (Greater Nechryael)',
      wikiPage: 'Greater Nechryael',
      transport: "Xeric's Heart / Kourend Castle teleport",
      why: 'Two 7-spawn chambers, multicombat, better drops than Tower nechs + shards/totems',
    },
    altLocation: {
      name: 'Slayer Tower (normal, melee)',
      wikiPage: 'Nechryael',
      transport: 'Slayer ring',
      why: 'Lazy melee option; Iorwerth Dungeon also burstable post-SotE',
    },
    inventoryExtras: ['Death rune', 'Chaos rune', 'Water rune', 'Prayer potion(4)', 'Herb sack', 'Ash sanctifier'],
    dangers: ['Death spawns chip you', 'Melee stacks hurt if Protect from Melee drops'],
    strategy: 'Tag all seven with the blowpipe, corner-dance them into a stack, Ice Burst the pile. One of the best burst tasks in the game.',
    keyDrops: ['Rune boots', 'Rune alchables', 'Herbs and seeds'],
    superior: 'Nechryarch',
    afk: 2,
    verdict: 'Top-tier xp — always do and extend.',
  },
  'Red dragons': {
    loadout: 'melee',
    gearMods: [{ slot: 'shield', item: 'Anti-dragon shield', why: 'Dragonfire protection with an antifire potion' }],
    protectPrayer: 'Optional with antifire + shield',
    offensivePrayer: 'Piety',
    cannon: 'Usable in Brimhaven Dungeon; not in the Catacombs.',
    bestLocation: {
      name: 'Brimhaven Dungeon',
      wikiPage: 'Red dragon',
      transport: 'Amulet of glory → Musa Point',
      why: 'Guaranteed bones + hide (~5k/kill); Karamja elite notes the hides; babies speed the count',
    },
    altLocation: {
      name: 'Forthos Dungeon',
      wikiPage: 'Forthos Dungeon',
      transport: "Xeric's Glade",
      why: 'Altar nearby',
    },
    inventoryExtras: ['Antifire potion(4)', 'Nature rune'],
    itemsRequired: ['Anti-dragon shield + antifire'],
    strategy: 'Melee with full dragonfire protection, loot every kill; rush with baby reds if you just want it done.',
    keyDrops: ['Dragon bones', 'Red dragonhide'],
    afk: 3,
    verdict: 'Low xp, small guaranteed profit — skip or rush.',
  },
  'Skeletal Wyverns': {
    loadout: 'crossbow',
    gearMods: [{ slot: 'shield', item: 'Elemental shield', why: 'Caps the icy breath (50+ unprotected) at 10 — DFS/dragonfire ward also work. NOT antifire potions.' }],
    protectPrayer: 'None when safespotted; Protect from Melee if meleeing',
    offensivePrayer: 'Rigour (ranging) / Piety (melee)',
    cannon: 'Allowed only in the LOWER (non-task-only) cave; the upper slayer area is no-cannon.',
    bestLocation: {
      name: 'Asgarnian Ice Dungeon (task-only upper area)',
      wikiPage: 'Skeletal Wyvern',
      transport: 'Port Sarim routes — entrance near Mudskipper Point',
      why: 'More spawns; known safespot one tile north-west of Steve',
    },
    altLocation: {
      name: 'Lower wyvern cave (cannon + melee)',
      wikiPage: 'Skeletal Wyvern',
      transport: 'Same entrance',
      why: 'Cannon permitted here',
    },
    inventoryExtras: ['Broad bolts', 'Ranging potion(4)', 'Prayer potion(4)', 'Nature rune'],
    itemsRequired: ['Elemental / Mind / Dragonfire shield (icy breath)', '72 Slayer'],
    dangers: ['Icy breath hits 50+ without the shield (5-tile range)', 'Hard melee too'],
    strategy: 'Wait out aggro (10 min), then lure behind an obstacle and safespot with the crossbow — their range is shorter than yours. Salve amulet does NOT work (animated, not undead).',
    keyDrops: ['Granite legs', 'Draconic visage (rare)', 'Noted magic logs'],
    afk: 3,
    verdict: 'Poor xp, decent gp — do for profit or skip.',
  },
  'Smoke devils': {
    loadout: 'burst',
    gearMods: [
      { slot: 'head', item: 'Slayer helmet (i)', why: 'REQUIRED (facemask-class) — otherwise constant stat-draining damage' },
      { slot: 'neck', item: 'Occult necklace', why: 'Magic damage % for barraging packs' },
    ],
    protectPrayer: 'Protect from Missiles',
    offensivePrayer: 'Augury / Mystic Might',
    cannon: 'Strongly recommended — place mid-dungeon to lure and aggro. (Destroyed if set up in the boss room.)',
    bestLocation: {
      name: 'Smoke Devil Dungeon',
      wikiPage: 'Smoke Devil Dungeon',
      transport: 'Ring of dueling → Castle Wars, run south-west',
      why: 'Only location; Castle Wars bank seconds away',
    },
    inventoryExtras: ['Blood rune', 'Death rune', 'Water rune', 'Prayer potion(4)', 'Cannonball'],
    itemsRequired: ['Facemask / Slayer helmet', '93 Slayer (task-only)'],
    strategy: 'Cannon aggros the cave, stack on a corner, Ice Barrage the pile — 120-180k slayer xp/hr, among the best tasks in the game. Occult drops (1/512) pay the runes.',
    keyDrops: ['Occult necklace (1/512)', 'Dragon chainbody (v. rare)'],
    superior: 'Nuclear smoke devil',
    bossAlt: 'Thermonuclear smoke devil (on-task at 93)',
    afk: 2,
    verdict: 'Premier barrage task — always do and extend once 93.',
  },
  'Spiritual creatures': {
    loadout: 'melee',
    gearMods: [{ slot: 'neck', item: 'Holy symbol', why: 'God-aligned item stops the wing\'s followers all attacking you at once' }],
    protectPrayer: 'Protect from Magic (kill only the mages)',
    offensivePrayer: 'Piety',
    cannon: 'No cannon in the God Wars Dungeon.',
    bestLocation: {
      name: "GWD — Saradomin's Encampment first room",
      wikiPage: 'Spiritual mage',
      transport: 'Trollheim teleport → GWD (Saradomin wing needs 70 Agility + rope)',
      why: 'Mages die fast to a whip and are the only spiritual creature worth killing (dragon boots)',
    },
    altLocation: {
      name: "Zamorak's Fortress (mages outside K'ril)",
      wikiPage: 'Spiritual mage',
      transport: 'Same entrance (70 HP crossing)',
      why: 'No 70 Agility needed',
    },
    inventoryExtras: ['Rope', 'Prayer potion(4)', 'Holy wrench'],
    itemsRequired: ['83 Slayer for mages', 'God-aligned item', 'Death Plateau'],
    dangers: ['Multicombat aggression without god items', 'Mixed styles drain supplies'],
    strategy: 'Kill only spiritual mages with the whip. Un-cannonable, un-AFKable, low xp and you can just buy dragon boots — prime block candidate for a main.',
    keyDrops: ['Dragon boots'],
    afk: 1,
    verdict: 'Block it — mains gain nothing here.',
  },
  Suqah: {
    loadout: 'melee',
    protectPrayer: 'Protect from Magic (north spawns) — tank the melee with your armour',
    offensivePrayer: 'Piety',
    cannon: 'Cannon the northern coast — 16 tight spawns, best xp/hr.',
    bestLocation: {
      name: 'Lunar Isle, northern coast',
      wikiPage: 'Suqah',
      transport: 'Moonclan Teleport (Lunar spellbook ✓)',
      why: 'Densest spawns — one of the better pure-xp cannon tasks at Duradel',
    },
    altLocation: {
      name: 'South, near the Astral altar',
      wikiPage: 'Suqah',
      transport: 'Moonclan Teleport, run south',
      why: 'Melee-only spawns — prayer-free AFK',
    },
    inventoryExtras: ['Cannonball', 'Prayer potion(4)', 'Super combat potion(4)'],
    itemsRequired: ['Lunar Diplomacy ✓'],
    strategy: 'Cannon the north side in melee gear with Protect from Magic; expect to lose gp — it is an xp task, drops are worthless.',
    keyDrops: ['Nothing notable'],
    afk: 3,
    verdict: 'Great cannon xp, zero profit.',
  },
  Trolls: {
    loadout: 'melee',
    protectPrayer: 'Protect from Melee',
    offensivePrayer: 'Piety',
    cannon: 'Very cannon-friendly at the Mount Quidamortem camp (multicombat).',
    bestLocation: {
      name: 'Mount Quidamortem troll camp',
      wikiPage: 'Mount Quidamortem',
      transport: "Xeric's talisman (Xeric's Honour) or Lovakengj minecart",
      why: '14 mountain trolls in tight multicombat — ideal cannon spot',
    },
    altLocation: {
      name: 'Ice trolls (Jatizso/Neitiznot)',
      wikiPage: 'Ice troll',
      transport: 'Fremennik Isles boats from Rellekka',
      why: 'Fastest troll xp, but unavoidable chip damage',
    },
    inventoryExtras: ['Cannonball', 'Super combat potion(4)', 'Prayer potion(4)'],
    strategy: 'Cannon + Protect from Melee + Piety and whip through the camp. Fast, cheap, brainless.',
    keyDrops: ['Nothing notable'],
    afk: 3,
    verdict: 'Fast easy xp — do, don\'t extend.',
  },
  TzHaar: {
    loadout: 'burst',
    gearMods: [{ slot: 'neck', item: 'Occult necklace', why: 'TzHaar-Ket have +0 magic defence — barrage shreds them' }],
    protectPrayer: 'Protect from Melee (bursting Kets)',
    offensivePrayer: 'Augury / Mystic Might',
    cannon: 'Not used — burst stacked Kets or safespot behind sulphur vents.',
    bestLocation: {
      name: 'Mor Ul Rek inner city (TzHaar-Ket)',
      wikiPage: 'TzHaar-Ket',
      transport: 'Fairy ring BLP (fire cape shown to enter the inner city)',
      why: 'Kets outnumber mages/rangers here — Protect from Melee blocks nearly everything',
    },
    altLocation: {
      name: 'TzHaar Fight Cave (1-3 TzTok-Jad option)',
      wikiPage: 'TzHaar Fight Cave',
      transport: 'Mor Ul Rek',
      why: '25,250 slayer xp per Jad with the helm active + pet/extra cape chance',
    },
    inventoryExtras: ['Blood rune', 'Death rune', 'Water rune', 'Prayer potion(4)'],
    itemsRequired: ['Hot stuff unlock (100 pts)'],
    dangers: ['Mej/Xil snipe you in bad stack spots', 'Jad option: one missed switch is death'],
    strategy: 'Barrage stacked Kets near the Ket-Rak Challenges, or take the 1-3 Jad assignment — you\'ve done the Fight Cave before, and each Jad is 25k slayer xp.',
    keyDrops: ['Obsidian gear', 'Uncut onyx (v. rare)', 'Fire cape (Jad)'],
    bossAlt: 'TzTok-Jad (offered as 1-3 kill assignment)',
    afk: 2,
    verdict: 'Good if you burst Kets or take Jads; otherwise skip the unlock.',
  },
  Vampyres: {
    loadout: 'melee',
    gearMods: [
      { slot: 'weapon', item: 'Blisterwood flail', why: 'MANDATORY — your whip cannot damage Vyrewatch Sentinels; only Ivandis/blisterwood-class weapons work' },
      { slot: 'ring', item: "Efaritay's aid", why: '15% accuracy vs vampyres, stacks with the slayer helm' },
    ],
    protectPrayer: 'Protect from Melee (Sentinels are melee-only)',
    offensivePrayer: 'Piety',
    bestLocation: {
      name: 'Darkmeyer (Vyrewatch Sentinels)',
      wikiPage: 'Vyrewatch Sentinel',
      transport: "Drakan's medallion",
      why: 'Blood shard drops + permanently aggressive melee-only mobs = very AFK; bank and altar in town',
    },
    inventoryExtras: ['Prayer potion(4)'],
    itemsRequired: ['Blisterwood flail (Sins of the Father)'],
    strategy: 'Don\'t unlock until Sins of the Father is done. Then AFK Sentinels with the flail under Protect from Melee, re-praying at the town altar. Salve amulet does nothing — vampyres aren\'t undead.',
    keyDrops: ['Blood shard (→ Amulet of blood fury)', 'Blood rune'],
    afk: 5,
    verdict: 'Extremely AFK and profitable once Sins of the Father is done.',
  },
  'Warped creatures': {
    loadout: 'melee',
    gearMods: [{ slot: 'head', item: 'Slayer helmet (i)', why: 'Earmuff-class protection halves Warped Terrorbird max hits' }],
    protectPrayer: 'Protect from Melee (tortoises) / Protect from Missiles (terrorbirds)',
    offensivePrayer: 'Piety',
    cannon: 'Good cannon task for terrorbirds — the waste-pit pathfinding traps them out of reach.',
    bestLocation: {
      name: 'Poison Waste Dungeon',
      wikiPage: 'Poison Waste Dungeon',
      transport: 'Spirit tree to the Poison Waste ✓ (The Path of Glouphrie)',
      why: 'Tortoises at the entrance for AFK; terrorbirds + cannon for xp',
    },
    inventoryExtras: ['Crystal chime', 'Cannonball', 'Prayer potion(4)'],
    itemsRequired: ['Crystal chime — they are INVULNERABLE without it in inventory', 'The Path of Glouphrie', 'Warped Reality unlock (60 pts)'],
    strategy: 'Chime in inventory or nothing dies. AFK the tortoises at the entrance, or cannon terrorbirds from the waste-pit safespot. Warped sceptre is a nice pickup.',
    keyDrops: ['Warped sceptre (uncharged)', 'Herbs/seeds'],
    afk: 3,
    verdict: 'Pleasant — AFK tortoises or fast cannon birds.',
  },
  Waterfiends: {
    loadout: 'melee',
    gearMods: [
      { slot: 'weapon', item: 'Zombie axe', why: 'Very low crush defence — whip slash is poor here; cheap crush swap wins' },
      { slot: 'body', item: "Karil's leathertop", why: 'Their magic AND magical-ranged attacks roll vs magic defence' },
    ],
    protectPrayer: 'Protect from Missiles (can\'t block both styles — expect chip damage)',
    offensivePrayer: 'Piety',
    cannon: 'No cannon anywhere useful (Ancient Cavern too damp; Iorwerth disallows).',
    bestLocation: {
      name: 'Iorwerth Dungeon',
      wikiPage: 'Waterfiend',
      transport: 'Prifddinas teleport crystal (SotE)',
      why: 'Tight spawns + bank/altar nearby',
    },
    altLocation: {
      name: 'Ancient Cavern',
      wikiPage: 'Ancient Cavern',
      transport: 'Games necklace → Barbarian Outpost, whirlpool dive',
      why: 'Pre-SotE default',
    },
    inventoryExtras: ['Prayer potion(4)', 'Super combat potion(4)'],
    itemsRequired: ['Barbarian Training progressed to pyre ships (assignment requirement)'],
    dangers: ['Dual-style unavoidable damage'],
    strategy: 'Crush weapon + d\'hide/Karil\'s, Protect from Missiles, grind them down. Supply-draining and weak drops.',
    keyDrops: ['Water rune', 'Crystal shard (Iorwerth)'],
    afk: 2,
    verdict: 'Rare, un-cannonable, mediocre — skip candidate (weight only 2).',
  },
  Wyrms: {
    loadout: 'blowpipe',
    gearMods: [{ slot: 'feet', item: 'Boots of stone', why: 'REQUIRED in the Karuulm Slayer Dungeon (waived by elite Kourend diary)' }],
    protectPrayer: 'Protect from Magic (from distance they only cast magic — fully negated)',
    offensivePrayer: 'Rigour / Eagle Eye',
    cannon: 'No cannon in the Karuulm Slayer Dungeon (unverified).',
    bestLocation: {
      name: 'Karuulm Slayer Dungeon (lower level)',
      wikiPage: 'Wyrm',
      transport: 'Fairy ring CIR at Mount Karuulm',
      why: 'Only location; bank at the mountain village',
    },
    inventoryExtras: ['Ranging potion(4)', 'Prayer potion(4)'],
    itemsRequired: ['Boots of stone', '62 Slayer'],
    strategy: 'Stand outside melee range and blowpipe with Protect from Magic — near-zero damage. On task, dragon sword/harpoon improve to 1/2,000 each.',
    keyDrops: ['Dragon sword (1/2,000 on task)', 'Dragon harpoon (1/2,000 on task)'],
    superior: 'Shadow Wyrm',
    afk: 4,
    verdict: 'Low-effort, damage-free, with dragon-weapon lottery tickets.',
  },
  'Boss tasks': {
    loadout: 'blowpipe',
    styleNote: 'Boss-specific — the helm bonus applies to every kill',
    protectPrayer: 'Boss-specific',
    offensivePrayer: 'Boss-specific',
    bestLocation: {
      name: 'Varies by assigned boss',
      wikiPage: 'Slayer task/Bosses',
      transport: 'Boss-specific',
      why: 'Duradel rolls an eligible boss; you pick the count (3-35, up to 65 with CA tiers)',
    },
    inventoryExtras: [],
    itemsRequired: ['Like a Boss unlock (200 pts)', 'Each boss\'s own requirements'],
    dangers: ['You can\'t choose which boss — a bad roll costs 30 points to skip'],
    strategy:
      'Finishing grants a bonus 5,000 slayer xp with the helm active throughout. Best rolls for your setup: Vorkath and Zulrah (money), Grotesque Guardians (needs a Brittle key first), Sarachnis and Dagannoth Kings (easy). Kraken (87), Cerberus (91), Thermonuclear (93) join the pool as your level allows. Set 3-5 kills on bosses you dislike; max out the money bosses.',
    keyDrops: ['Boss uniques — Vorkath/Zulrah gp, Kraken trident, Cerberus boot crystals'],
    afk: 1,
    verdict: 'Unlock once you have 200 spare points — best gp/task at Duradel.',
  },
}
